### ISSUE TITLE
I did not try `PyPDF2`. Does it work?

### ISSUE THREAD

**Issue by lzblack** [sgriffin10/ProblemSolving#2]
Just curious

**Comment by sgriffin10** [comment]
Hi Prof,

Apologies for the lack of context, I was using the python concepts we learned in class to slice and merge PDFs for an upcoming exam. While this is completely irrelevant to our session 12 exercises, I did have to move the pdfs to the session12 folder because my code was not working on another folder. 

And yes, I managed to get it to work. pdf_tester2.py is the code I used to create MetaCombinedResults.pdf! pdf_tester.py was the original code (which is much cleaner) I got from stack overflow but did not work even though I tweaked it about 20 times. Feel free to take a look.

**Comment by lzblack** [comment]
No need to apologize. It is great that you try some other modules and do some exploration. I will take a look at your code later.

**Comment by lzblack** [comment]
I found the issue in `pdf_tester.py`.

Change 
```
    # appending pdfs one by one 
    for pdf in pdfs: 
        with open(pdf, 'rb') as f: 
            pdfMerger.append(f) 
```
to
```
    # appending pdfs one by one 
    for pdf in pdfs:
        pdfMerger.append(pdf) 
```
